[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "atb-lib"
version = "0.6.12"
description = "A Python package for Advanced Trading Bot"
readme = "README.md"
authors = [{name = "Yuriy Tigiev", email = "yuriy.tigiev@outlook.com"}]
license = {file = "LICENSE"}
keywords = ["crypto", "exchange", "trading", "bot", "package"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
]
dependencies = [
    "colorlog>=6.8.2",
    "aio_pika>=9.4.0",
    "asyncio>=3.4.3",
    "importlib-metadata>=7.0.1",
    "uvicorn>=0.27.1",
    "fastapi>=0.109.2",
    "websockets>=12.0",
    "pip>=24.0.0",
    "arrow>=1.3.0",
    "msgpack>=1.0.7",
    "wheel>=0.42.0",
]

[project.urls]
homepage = "https://github.com/YuriyTigiev/atb_lib"

[project.optional-dependencies]
extras = []
