[project]
name = "sdmc_adhoc_processing"
version = "0.1.3"
authors = [
  { name="Beatrix Haddock", email="beatrix.haddock@gmail.com" },
]
description = "Helper utilities for SDMC ad-hoc data processing requests."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/beatrixh/sdmc-adhoc-processing"

[build-system]
requires = ["hatchling", "pandas", "typing", "datetime"]
build-backend = "hatchling.build"
