[tool.poetry]
name = "pynatrace"
version = "1.8.0"
description = "Python limited CLI for Dynatrace"
authors = ["Michael MacKenna <mmackenna@unitedfiregroup.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
click = "^8.1.3"
termcolor = "^2.2.0"
dt = "^1.1.48"

[tool.poetry.dev-dependencies]
pylint = "^2.13.9"
ipython = "^8.3.0"
black = "^22.3.0"
jupyter = "^1.0.0"
mdv = "^1.7.4"

[tool.poetry.scripts]
pynatrace = 'pynatrace.cli:main'

[tool.poetry.group.dev.dependencies]
mkdocs = "^1.4.3"
mkdocs-click = "^0.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
