[build-system]
build-backend = "cmeel"
requires = [
  "cmeel-assimp >= 5.3.1, < 6",
  "cmeel-boost ~= 1.83.0",
  "cmeel-octomap >= 1.9.8.2, < 2",
  "cmeel-qhull >= 8.0.2.1, < 8.0.3",
  "cmeel[build]",
  "eigenpy[build] >= 3.1, < 4"
]

[project]
dependencies = [
  "cmeel-assimp >= 5.3.1, < 6",
  "cmeel-boost ~= 1.83.0",
  "cmeel-octomap >= 1.9.8.2, < 2",
  "cmeel-qhull >= 8.0.2.1, < 8.0.3",
  "eigenpy >= 3.1, < 4"
]
description = " An extension of the Flexible Collision Library"
license = "BSD-3-Clause"
name = "hpp-fcl"
version = "2.4.4"

[project.urls]
changelog = "https://github.com/humanoid-path-planner/hpp-fcl/blob/master/CHANGELOG.md"
homepage = "https://github.com/cmake-wheel/hpp-fcl"
upstream = "https://github.com/humanoid-path-planner/hpp-fcl"

[tool.cmeel]
build-number = 1
configure-args = ["-DHPP_FCL_HAS_QHULL=ON"]

[tool.tomlsort]
all = true
