[project]
name = "luca_api"
version = "0.0.8"
authors = [
    { name="HorusAI", email="quyennt@horusvn.com" },
]
description = "Robot Luca API package"
readme = "README.md"
#requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

