# pyproject.toml

[build-system]
requires = ["setuptools>=69.1.1", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/"]
include = ["aett.mongodb"]

[project]
name = "aett-mongodb"
version = "0.3.0"
description = "MongoDB connector for aett event store"
readme = "README.md"
authors = [{ name = "Jacob Reimers", email = "pypi@reimers.io" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["events", "event store", "dynamodb"]
dependencies = [
    'typing >= 3.7.4.3',
    'jsonpickle >= 3.0.3',
    'aett-domain >= 0.3.0',
    'pymongo~=4.6.2'
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/jjrdk/aett"

[project.scripts]
