[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "neuralplex"
version = "0.0.4"
authors = [
  { name="FAR Analytics & Research", email="adam@farar.net" },
]
description = "A Neuralplex."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/faranalytics/neuralplex"
Issues = "https://github.com/faranalytics/neuralplex/issues"