[tool.poetry]
name = "webql"
version = "0.2.5"
description = "Tiny Fish WebQL Python Client"
authors = []
license = "MIT"
readme = "PACKAGE_README.md"

[tool.poetry.dependencies]
python = "^3.8"
playwright = "^1.0.0"
requests = "^2.31.0"
pydantic = "^2.5"
httpx = "^0.26.0"
pytest-asyncio = "^0.23.5"
aiofiles = "^23.2.1"
playwright-stealth = "^1.0.6"

[tool.poetry.group.dev.dependencies]
black = "*"


[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-time = "*"
pylint = "*"
mockito = "*"
pytest_env = "*"
pytest-asyncio = "*"
html-to-json = "*"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["test"]

[tool.pytest_env]
WEBQL_API_KEY = "test"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
