[build-system]
requires = ["setuptools >= 61.0", "wheel", "setuptools_scm[toml]", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "kepderiv"
version = "1.0.6"
authors = [
  { name = "Jean-Baptiste Delisle", email = "jean-baptiste.delisle@unige.ch" },
]
description = "Keplerian modeling and derivatives for radial velocities and astrometry analyses."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)",
  "Operating System :: OS Independent",
]
dependencies = ["numpy>=1.16"]

[project.urls]
Homepage = "https://gitlab.unige.ch/delisle/kepderiv"
Issues = "https://gitlab.unige.ch/delisle/kepderiv/-/issues"
