[tool.poetry]
name = "kvcommon"
version = "0.0.6"
description = "Library of miscellaneous common python utils that aren't worthy of their own dedicated libs."
authors = ["Rob Voigt <code@ravoigt.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
black = "*"
ipdb = "*"
ipython = "*"
mock = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
pyfakefs = "*"


[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
