[project]
name = "tkinter_qu"
version = "1.0.16"
authors = [
    { name="Micah Ribbens", email="mdribbens22@outlook.com" },
]
description = ""
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Micah-Ribbens/Tkinter-Qu"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"