[tool.poetry]
name = "approck-fastapi-utils"
version = "0.1.0"
description = ""
authors = ["Aleksey Dalekin <adalekin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
fastapi = "^0.109.2"
python = "^3.10"

[tool.poetry.dev-dependencies]
mypy = "^1.1.1"
pre-commit = "^3.1.0"
pytest = "^7.2.2"
ruff = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
